name: Run Tests on traffic-light-system changes

on:
  push:
    paths:
      - 'traffic-light-system/**'
  pull_request:
    paths:
      - 'traffic-light-system/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew
        working-directory: traffic-light-system

      - name: Build and run tests
        run: ./gradlew test
        working-directory: traffic-light-system