name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:               

jobs:
  run-tests-traffic-light-system:
    if: github.event_name != 'push' || contains(github.event.head_commit.message, 'traffic-light-system') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Run Tests on traffic-light-system changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew
        working-directory: traffic-light-system

      - name: Build and run tests
        run: ./gradlew test
        working-directory: traffic-light-system

  publish-cli-jar:
    needs: run-tests-traffic-light-system
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Publish CLI JAR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew
        working-directory: traffic-light-system

      - name: Build and publish
        run: ./gradlew publish
        working-directory: traffic-light-system
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
